version: '2'
networks:
  composer_default:
services:
  medichain-rest-server:
    image: medichain/medichain-composer-rest-server
    container_name: medichain-rest-server
    ports:
      - 3001:3000
    environment:
      - COMPOSER_CARD=admin@medichain
      - COMPOSER_NAMESPACES=always
      - COMPOSER_AUTHENTICATION=false
      - COMPOSER_MULTIUSER=false
    volumes:
      - ~/.composer:/home/composer/.composer
    networks:
      - composer_default