version: '2'
networks:
  composer_default:
services:
  medichain-rest-server:
    image: medichain/medichain-composer-rest-server
    container_name: medichain-rest-server
    ports:
      - 3000:3000
    environment:
      - COMPOSER_CARD=admin@medichain
      - COMPOSER_NAMESPACES=always
      - COMPOSER_AUTHENTICATION=true
      - COMPOSER_MULTIUSER=true
      - COMPOSER_PROVIDERS="${COMPOSER_PROVIDERS}"
      - COMPOSER_DATASOURCES="${COMPOSER_DATASOURCES}"
    volumes:
      - ~/.composer:/home/composer/.composer
    networks:
      - composer_default